apiVersion: v2
name: secrets-store-csi-driver
version: 1.2.0
appVersion: 1.2.0
kubeVersion: ">=1.16.0-0"
description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes cluster.
icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
sources:
  - https://github.com/kubernetes-sigs/secrets-store-csi-driver
maintainers:
  - name: Rita Zhang
    email: ritazh@microsoft.com
