image:
  repository: docker.io/deislabs/secrets-store-csi
  tag: v0.0.9
  pullPolicy: Always

logLevel:
  debug: true

livenessProbe:
  port: 9808

## Install Default RBAC roles and bindings
rbac:
  install: true

## Minimum Provider Versions (optional)
## A comma delimited list of key-value pairs of minimum provider versions
## e.g. provider1=0.0.2,provider2=0.0.3
minimumProviderVersions:
