image:
  repository: docker.io/deislabs/secrets-store-csi
  tag: v0.0.5
  pullPolicy: Always

logLevel: 

## Install Default RBAC roles and bindings
rbac:
  install: true

## providers supported
providers:
  azure:
    enabled: false
    repository: aramase/secrets-store-csi-driver-provider-azure
    tag: v0.0.6
    imagePullPolicy: Always

  vault:
    enabled: false
    repository: hashicorp/secrets-store-csi-driver-provider-vault
    tag: 0.0.2
    imagePullPolicy: Always
