# This is the config map for the allow policy. These values will be passed to the helm chart.
# The config map is an easy way to provide an example of the configuration.
# It is used to configure the controllerName, controllerNamespace parameters and the list of secret types to allow.
# The user must configure:
#   the controllerName and controllerNamespace parameters
#   the list of secret types to allow
# These pre-configured types are currently supported by the Secret Store CSI Driver. 
# We don't want to allow the creation of any other types of secrets: e.g. service-account-tokens
apiVersion: v1
kind: ConfigMap
metadata:
  name: "admission-policies-secret-sync-controller-allow-config"
data:
  controllerName: 'secret-sync-controller'               # This is the name of the controller. It is formatted in the policy as: system:serviceaccount:NS_NAME:secret-store-sync-controller
  controllerNamespace: 'secret-sync-controller'          # This is the namespace where the secret-sync-controller is running
  secretTypeOpaque: 'Opaque'
  secretTypeBasicAuth: 'kubernetes.io/basic-auth'
  secretTypeBootstrapToken: 'bootstrap.kubernetes.io/token'
  secretTypeDockerConfigJson: 'kubernetes.io/dockerconfigjson'
  secretTypeDockerCfg: 'kubernetes.io/dockercfg'
  secretTypeSSHAuth: 'kubernetes.io/ssh-auth'
  secretTypeTLS: 'kubernetes.io/tls'