version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    labels:
      - "ok-to-test"

  - package-ecosystem: "gomod"
    directory: "/hack/tools"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    labels:
      - "ok-to-test"

  - package-ecosystem: docker
    directory: /.local
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    labels:
      - "ok-to-test"

  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    labels:
      - "ok-to-test"

  - package-ecosystem: docker
    directory: /test/e2eprovider
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    labels:
      - "ok-to-test"

  - package-ecosystem: gomod
    directory: /test/e2eprovider
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    labels:
      - "ok-to-test"
