# This policy is used to prevent the secret-sync-controller from deleting secrets.
# It requires the parameter controllerName and controllerNamespace to be set in the
# ConfigMap admission-policies-secret-sync-controller-config.
# The user must configure:
#   the controllerName and controllerNamespace parameters
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingAdmissionPolicy
metadata:
  name: "secret-sync-controller-delete-policy"
spec:
  failurePolicy: Fail
  paramKind:
    apiVersion: v1
    kind: ConfigMap 
  matchConditions:
    - name: 'userIsController'
      expression: "request.userInfo.username == 'system:serviceaccount:'+params.data.controllerNamespace+':'+params.data.controllerName"
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["DELETE"]
      resources:   ["secrets"]
  validations:
  - expression: "false" # if the expression evaluates to false, the validation check is enforced according to the failurePolicy
    message: "The controller is not allowed to delete secrets."
    messageExpression: string(params.data.controllerName)  + ' has failed to ' +  string(request.operation) + ' secrets in the ' + string(request.namespace) + ' namespace. The controller is not allowed to delete secrets.'
    reason: "Forbidden"
---
#Helm version
#{{- if .Values.validatingAdmissionPolicies.applyPolicies -}}
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingAdmissionPolicy
metadata:
  name: "secret-sync-controller-delete-policy"
spec:
  failurePolicy: Fail
  matchConditions:
    - name: 'userIsController'
      expression: {{ include "chartname.matchConditionExpression" . | quote }}
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["DELETE"]
      resources:   ["secrets"]
  validations:
  - expression: "false"
    message: "The controller is not allowed to delete secrets."
    messageExpression: "'secret-sync-controller has failed to ' +  string(request.operation) + ' secrets in the ' + string(request.namespace) + ' namespace. The controller is not allowed to delete secrets.'"
#{{- end -}}