kind: Pod
apiVersion: v1
metadata:
  name: nginx-secrets-store
spec:
  containers:
  - image: nginx
    name: nginx-secrets-store
    volumeMounts:
    - name: secrets-store01
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
  - name: secrets-store01
    persistentVolumeClaim:
      claimName: pvc-secrets-store
