apiVersion: v1
entries:
  secrets-store-csi-driver:
  - apiVersion: v2
    appVersion: 1.1.0
    created: "2022-02-23T19:42:32.615911697Z"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: c82c3c45a52b64df400b2cff7b00c3249b8a6409fbba797eef0a51df02b2949b
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts/secrets-store-csi-driver-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v2
    appVersion: 1.1.0-rc.0
    created: "2022-02-23T19:42:32.614577491Z"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 5246dfc14560dda3b5008f5dc852f135eb2090582f77fc4487557737bac53364
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts/secrets-store-csi-driver-1.1.0-rc.0.tgz
    version: 1.1.0-rc.0
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2022-02-23T19:42:32.613004485Z"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 3ede4fec9c9900016700a39bcf6f9341b8478c4f161f68f7cf6c1203d01c5247
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts/secrets-store-csi-driver-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2022-02-23T19:42:32.611289578Z"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 3dd377635c228a7c4a3e8ecb5221868b2a1a30d3279d1b3c3cac81b657562e04
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts/secrets-store-csi-driver-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v2
    appVersion: 1.0.0-rc.1
    created: "2022-02-23T19:42:32.609549271Z"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: f35f64d2c1cfec2e9a55b6304b993a0c96b54266ee47768461e8d5d7fe7067ea
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts/secrets-store-csi-driver-1.0.0-rc.1.tgz
    version: 1.0.0-rc.1
  - apiVersion: v2
    appVersion: 1.0.0-rc.0
    created: "2022-02-23T19:42:32.608229865Z"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 51aa40e2997f67bd0068cd7f6ba2304cf681101978f901e2c90d2e5ca25ffd1e
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts/secrets-store-csi-driver-1.0.0-rc.0.tgz
    version: 1.0.0-rc.0
  - apiVersion: v2
    appVersion: 0.3.0
    created: "2022-02-23T19:42:32.60697646Z"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 688cb678d7b14cc9ee3890de0ca4a5e925c41e20ae8a3e45b843905ea4bdfd6a
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts/secrets-store-csi-driver-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 0.2.0
    created: "2022-02-23T19:42:32.605758155Z"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 00d1d13ddaeb7ea41172b9f60faa92b682d9348221f1f982672ebc8930ad79f1
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts/secrets-store-csi-driver-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2022-02-23T19:42:32.60451415Z"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 4a8afc66ad5d9b42c3759213520da7024e966dbe0ab13a005f03fe32b10fac2e
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts/secrets-store-csi-driver-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v1
    appVersion: 0.0.23
    created: "2022-02-23T19:42:32.602885944Z"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 8207abf0e14ffe7d828119937e11fa72340d19d824e9a326b8f40fc8b6c8bd86
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts/secrets-store-csi-driver-0.0.23.tgz
    version: 0.0.23
  - apiVersion: v1
    appVersion: 0.0.22
    created: "2022-02-23T19:42:32.601734039Z"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: e0df45a819f1fd99976bc26fc3b06b4d3ab8034d48829ed62b168dee79d96b88
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts/secrets-store-csi-driver-0.0.22.tgz
    version: 0.0.22
  - apiVersion: v1
    appVersion: 0.0.21
    created: "2022-02-23T19:42:32.599849531Z"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: cab95625686b388faa1e298dc913a14c5b28ffff7888074664e98dc392c94814
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts/secrets-store-csi-driver-0.0.21.tgz
    version: 0.0.21
  - apiVersion: v1
    appVersion: 0.0.20
    created: "2022-02-23T19:42:32.598455226Z"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: b08ef96a751c05859ea3cb21b5e39d11c9a66ad033ff020ee5f7ecbffb761aa1
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts/secrets-store-csi-driver-0.0.20.tgz
    version: 0.0.20
  - apiVersion: v1
    appVersion: 0.0.19
    created: "2022-02-23T19:42:32.596882719Z"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 0070b72ba43a76e8bcda9e06d68dcbb27a2893954ffe92e7b30aae8c0012593b
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts/secrets-store-csi-driver-0.0.19.tgz
    version: 0.0.19
  - apiVersion: v1
    appVersion: 0.0.18
    created: "2022-02-23T19:42:32.595938315Z"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 1f096be8bb4afdb001f03d0074f1629ad0fa6459388862df3e3ad5f98b4288cf
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts/secrets-store-csi-driver-0.0.18.tgz
    version: 0.0.18
  - apiVersion: v1
    appVersion: 0.0.17
    created: "2022-02-23T19:42:32.595012212Z"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: d83ee8e6e436c90350c5371a9e597663bd586286a1e9f851a6010eb79f3c9244
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts/secrets-store-csi-driver-0.0.17.tgz
    version: 0.0.17
  - apiVersion: v1
    appVersion: 0.0.16
    created: "2022-02-23T19:42:32.594105408Z"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 28801272b580f6c5a8ec7cf634b05176debf8b7e92724847f594512ac081171c
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts/secrets-store-csi-driver-0.0.16.tgz
    version: 0.0.16
  - apiVersion: v1
    appVersion: 0.0.15
    created: "2022-02-23T19:42:32.593216704Z"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 155ead450f2f8824f99f8508a11d14ae703084a5b95d7dbac391658199cf4a9a
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts/secrets-store-csi-driver-0.0.15.tgz
    version: 0.0.15
  - apiVersion: v1
    appVersion: 0.0.14
    created: "2022-02-23T19:42:32.592289301Z"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 6390ebd13eeb76d1ed22263831d5383f8258bec1731d4f98e6c8dfe8b6256249
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts/secrets-store-csi-driver-0.0.14.tgz
    version: 0.0.14
  - apiVersion: v1
    appVersion: 0.0.13
    created: "2022-02-23T19:42:32.591372897Z"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 426ea403ad1083cae569a13d8ecf686e4797b7816f6254709070afc4f4b858ab
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.15.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts/secrets-store-csi-driver-0.0.13.tgz
    version: 0.0.13
  - apiVersion: v1
    appVersion: 0.0.12
    created: "2022-02-23T19:42:32.590652194Z"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 0c132d4be8c4eb48109a4fe8cc0ce29e6fc9f68647bb522c4040d033861a0e78
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.15.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts/secrets-store-csi-driver-0.0.12.tgz
    version: 0.0.12
  - apiVersion: v1
    appVersion: 0.0.11
    created: "2022-02-23T19:42:32.590121792Z"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 2751ae7aed8ea2fc7dcdcbbf26240fccb2eefd83d3943cef45bb58bb1d297692
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.15.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts/secrets-store-csi-driver-0.0.11.tgz
    version: 0.0.11
  - apiVersion: v1
    appVersion: 0.0.10
    created: "2022-02-23T19:42:32.58959169Z"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 9fae95e4611c9c120ed12505e735680b70ed133ea987fd32db05046cb45eda9e
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.15.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts/secrets-store-csi-driver-0.0.10.tgz
    version: 0.0.10
  - apiVersion: v1
    appVersion: 0.0.9
    created: "2022-02-23T19:42:32.603338545Z"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 0f74454ca36c979a352d8a7b6d847521897ebf78195527ed8946201a841887a7
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.15.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts/secrets-store-csi-driver-0.0.9.tgz
    version: 0.0.9
generated: "2022-02-23T19:42:32.588914987Z"
