apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: secret-sync-controller
    app.kubernetes.io/instance: system
    app.kubernetes.io/name: namespace
    app.kubernetes.io/part-of: secret-sync-controller
    control-plane: controller-manager
    secrets-store.io/system: "true"
  name: {{ .Values.namespace }}