{{- if .Values.windows.enabled}}
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: {{ template "sscd.fullname" . }}-windows
  namespace: {{ .Release.Namespace }}
{{ include "sscd.labels" . | indent 2 }}
spec:
  selector:
    matchLabels:
      app: {{ template "sscd.name" . }}
  template:
    metadata:
{{ include "sscd.labels" . | indent 6 }}
    spec:
      serviceAccountName: secrets-store-csi-driver
      containers:
        - name: node-driver-registrar
          image: mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v1.2.1-alpha.1-windows-1809-amd64
          args:
            - --v=5
            - "--csi-address=unix://C:\\csi\\csi.sock"
            - --kubelet-registration-path={{ .Values.windows.kubeletRootDir }}\plugins\csi-secrets-store\csi.sock
          lifecycle:
              preStop:
                exec:
                  command:
                    [
                      "cmd",
                      "/c",
                      "del /f C:\\registration\\secrets-store.csi.k8s.io-reg.sock",
                    ]
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          imagePullPolicy: Always
          volumeMounts:
            - name: plugin-dir
              mountPath: C:\csi
            - name: registration-dir
              mountPath: C:\registration
        - name: secrets-store
          image: "{{ .Values.windows.image.repository }}:{{ .Values.windows.image.tag }}"
          args:
            - "--debug={{ .Values.logLevel.debug }}"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nodeid=$(KUBE_NODE_NAME)"
            - "--provider-volume=C:\\k\\secrets-store-csi-providers"
            {{- if and (semverCompare ">= v0.0.9-0" .Values.windows.image.tag) .Values.minimumProviderVersions }}
            - "--min-provider-version={{ .Values.minimumProviderVersions }}"
            {{- end }}
            - "--metrics-addr={{ .Values.windows.metricsAddr }}"
          env:
            - name: CSI_ENDPOINT
              value: unix://C:\\csi\\csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          imagePullPolicy: {{ .Values.windows.image.pullPolicy }}
          securityContext:
            privileged: true
          {{- if semverCompare ">= v0.0.9-0" .Values.windows.image.tag }}
          ports:
            - containerPort: {{ .Values.livenessProbe.port }}
              name: healthz
              protocol: TCP
          livenessProbe:
              failureThreshold: 5
              httpGet:
                path: /healthz
                port: healthz
              initialDelaySeconds: 30
              timeoutSeconds: 10
              periodSeconds: 15
          {{- end }}
          volumeMounts:
            - name: plugin-dir
              mountPath: C:\csi
            - name: mountpoint-dir
              mountPath: {{ .Values.windows.kubeletRootDir }}\pods
              mountPropagation: Bidirectional
            - name: providers-dir
              mountPath: C:\k\secrets-store-csi-providers
        {{- if semverCompare ">= v0.0.9-0" .Values.windows.image.tag }}
        - name: liveness-probe
          image: mcr.microsoft.com/oss/kubernetes-csi/livenessprobe:v2.0.1-alpha.1-windows-1809-amd64
          imagePullPolicy: Always
          args:
          - "--csi-address=unix://C:\\csi\\csi.sock"
          - --probe-timeout=3s
          - --health-port={{ .Values.livenessProbe.port }}
          volumeMounts:
            - name: plugin-dir
              mountPath: C:\csi
        {{- end }}
      volumes:
        - name: mountpoint-dir
          hostPath:
            path: {{ .Values.windows.kubeletRootDir }}\pods\
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: {{ .Values.windows.kubeletRootDir }}\plugins_registry\
            type: Directory
        - name: plugin-dir
          hostPath:
            path: {{ .Values.windows.kubeletRootDir }}\plugins\csi-secrets-store\
            type: DirectoryOrCreate
        - name: providers-dir
          hostPath:
            path: C:\k\secrets-store-csi-providers\
            type: DirectoryOrCreate
      nodeSelector:
        kubernetes.io/os: windows
{{- if .Values.windows.nodeSelector }}
{{- toYaml .Values.windows.nodeSelector | nindent 8 }}
{{- end }}
{{- with .Values.windows.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- end -}}
