{{ if .Values.rbac.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-store-csi-driver
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "sscd.labels" . | indent 4 }}
{{ end }}
